[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build/"

[[redirects]]
  from = "/convert"
  to = "/.netlify/functions/convert"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200